#!/usr/bin/env node
// Card A19-R — v0.2 Web Surface client-side enhancement bundler.
//
// Compiles ``web/src/client/enhance.ts`` to
// ``web/assets/v0.2/app.js`` via esbuild's transform API
// (loader=ts, format=iife, target=es2020, minify=false).
//
// Why we generate (rather than hand-mirror) and commit the output:
//   * Single source of truth: ``enhance.ts`` is the editor file;
//     the JS asset is a deterministic projection of it.
//   * The asset router serves ``app.js`` via the existing
//     fingerprinted manifest pipeline (Card A9/A10). The
//     manifest must regenerate after any change here so the
//     ``{{ app_js }}`` URL in the layout points at the new
//     fingerprint.
//   * The output is committed (mirrors the manifest.json
//     pattern). The CI guard at
//     ``web/scripts/build-client.mjs`` + ``npm run client:check``
//     fails any merge that ships an out-of-date asset.
//
// Determinism contract:
//   * Same input bytes → same output bytes, byte-for-byte.
//   * Format set explicitly (iife / target es2020 / no
//     sourcemap / minify off) so esbuild's defaults can't
//     introduce drift.
//   * Single trailing newline, fixed banner.
//
// Usage:
//
//     npm run client:gen     # regenerate app.js
//     npm run client:check   # regenerate + git-diff drift gate
//
// IMPORTANT — manifest interaction:
//   The asset manifest at ``web/assets/v0.2/manifest.json``
//   carries a content-hash of app.js. If you re-run this
//   script and the output changes, you MUST also re-run
//   ``npm run assets:gen`` to refresh the manifest. The repo's
//   asset-manifest drift gate
//   (``scripts/check_asset_manifest.sh``) will fail otherwise.

import { transform } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const WEB_ROOT = resolve(__dirname, "..");

const SOURCE_PATH = resolve(WEB_ROOT, "src/client/enhance.ts");
const OUTPUT_PATH = resolve(WEB_ROOT, "assets/v0.2/app.js");


const BANNER = [
  "/* ClarityOS v0.2 Web Surface — client-side enhancement.",
  " * Generated from web/src/client/enhance.ts via",
  " * web/scripts/build-client.mjs. DO NOT EDIT THIS FILE BY HAND;",
  " * edit the TS source and re-run ``npm run client:gen``.",
  " */",
].join("\n");


async function main() {
  let source;
  try {
    source = readFileSync(SOURCE_PATH, "utf-8");
  } catch (err) {
    console.error(`✗ failed to read source: ${SOURCE_PATH}\n  ${err.message}`);
    process.exit(1);
  }

  let result;
  try {
    result = await transform(source, {
      loader:        "ts",
      format:        "iife",
      target:        "es2020",
      minify:        false,
      sourcemap:     false,
      legalComments: "none",
      // Make output dependent ONLY on input bytes — no
      // filename-embedding, no path-embedding.
      sourcefile:    "enhance.ts",
    });
  } catch (err) {
    console.error(`✗ esbuild transform failed:\n  ${err.message}`);
    process.exit(1);
  }

  // Compose the final asset: banner + transformed code, with a
  // single trailing newline. ``result.code`` already ends in
  // ``\n`` when esbuild generates output, but trim and re-add
  // for byte-stable framing.
  const body = result.code.replace(/\n+$/, "");
  const out  = `${BANNER}\n${body}\n`;

  try {
    writeFileSync(OUTPUT_PATH, out);
  } catch (err) {
    console.error(`✗ failed to write asset: ${OUTPUT_PATH}\n  ${err.message}`);
    process.exit(1);
  }

  const relPath = OUTPUT_PATH
    .replace(WEB_ROOT + "/", "")
    .replace(WEB_ROOT + "\\", "");
  console.log(
    `✓ wrote ${relPath} (${out.length} bytes; remember to run ` +
    `\`npm run assets:gen\` to refresh manifest)`,
  );
}

await main();
